name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug
          
      - name: Install secp256k1_nostr extension for PHP
        run: sudo apt install autoconf build-essential git libtool pkgconf

      - name: Clone secp256k1_nostr extension for PHP repository
        uses: actions/checkout@v4
        with:
          repository: '1ma/secp256k1-nostr-php'
          ref: 'v0.1.3'
          path: 'build/1ma/secp256k1-nostr-php'

      - name: Init secp256k1_nostr extension for PHP
        working-directory: ./build/1ma/secp256k1-nostr-php
        run: |
          git submodule init
          git submodule update

      - name: Build secp256k1_nostr extension for PHP
        working-directory: ./build/1ma/secp256k1-nostr-php
        run: |
          make secp256k1 ext
          make check

      - name: Install secp256k1_nostr extension for PHP
        working-directory: ./build/1ma/secp256k1-nostr-php
        run: sudo make install

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug
          ini-values: extension=secp256k1_nostr.so

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare test environment
        run: |
          mkdir ./logs
          mkdir ./data
          mkdir ./data/events
          mkdir ./data/files
          
      - name: Tests
        run: ./vendor/bin/pest
